version: "3"

services:
  network_info:
    image: network_info
    build:
      context: .
    command: -c postgresql+psycopg://network_info:network_info@db:5432/network_info
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: network_info
      POSTGRES_USER: network_info
      POSTGRES_PASSWORD: network_info
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
